### ISSUE TITLE
Swipe issue

### ISSUE THREAD

**Issue by karthisammannan** [hudomju/android-swipe-to-dismiss-undo#13]
Swipe left and right not work in recyclerview..abstract method not implemented
            at com.hudomju.swipe.SwipeableItemClickListener.onRequestDisallowInterceptTouchEvent(SwipeableItemClickListener.java)

**Comment by alchemistake** [comment]
When this happens? i have a tabbed activity when it happens is it about that?

**Comment by alchemistake** [comment]
I fixed it with a nooby approach it will hold until next update hopefully...
Create a class like this and use it. You are good to go

public class SwipeableItemClickListener extends com.hudomju.swipe.SwipeableItemClickListener {
    public SwipeableItemClickListener(Context context, OnItemClickListener listener) {
        super(context, listener);
    }

```
@Override
public void onRequestDisallowInterceptTouchEvent(boolean disallowIntercept) {

}
```

}

**Comment by KoWu** [comment]
There is an easier solution. Simply override the Method at instanciation time. You don't need to write an own class.

```
recyclerView.addOnItemTouchListener(
new SwipeableItemClickListener(getActivity(),
new OnItemClickListener() {
      @Override
      public void onItemClick(View view, int i) {
        //do stuff
      }
    }) {
      @Override
      public void onRequestDisallowInterceptTouchEvent(boolean disallowIntercept) {
    }
});
```

ugly but effective.

**Comment by alchemistake** [comment]
I loved your solution but i use this class in 4 different places rather than rewrite own class looked more effective to me. You thought me something today thanks :)
