### ISSUE TITLE
I have two issues when add this Library

### ISSUE THREAD

**Issue by RajeshRajendiran** [hudomju/android-swipe-to-dismiss-undo#4]
Problem 1: Minimum SDK only 15 any chance to change 14
Problem 2: I got another error is
:financeapp:preBuild UP-TO-DATE
:financeapp:preDebugBuild UP-TO-DATE
:financeapp:compileDebugNdk UP-TO-DATE
:financeapp:checkDebugManifest
:financeapp:preReleaseBuild UP-TO-DATE
:financeapp:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:financeapp:prepareComAndroidSupportRecyclerviewV72200Library UP-TO-DATE
:financeapp:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:financeapp:prepareComGoogleAndroidGmsPlayServices6587Library UP-TO-DATE
:financeapp:prepareComHudomjuSwipeToDismissUndo10Library UP-TO-DATE
:financeapp:prepareDebugDependencies
:financeapp:compileDebugAidl UP-TO-DATE
:financeapp:compileDebugRenderscript UP-TO-DATE
:financeapp:generateDebugBuildConfig UP-TO-DATE
:financeapp:generateDebugAssets UP-TO-DATE
:financeapp:mergeDebugAssets UP-TO-DATE
:financeapp:generateDebugResValues UP-TO-DATE
:financeapp:generateDebugResources UP-TO-DATE
:financeapp:mergeDebugResources UP-TO-DATE
:financeapp:processDebugManifest UP-TO-DATE
:financeapp:processDebugResources UP-TO-DATE
:financeapp:generateDebugSources UP-TO-DATE
:financeapp:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:financeapp:preDexDebug
:financeapp:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/hudomju/swipe/adapter/ViewAdapter;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':financeapp:dexDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_11\bin\java.exe'' finished with non-zero exit value 2
> Information:BUILD FAILED
> Information:Total time: 58.415 secs
> Information:1 error
> Information:0 warnings
> Information:See complete output in console

**Comment by hongchainan** [comment]
Did you fix this?
If you fix it,please let me know about this problem.
